### ISSUE TITLE
Auth module config settings

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring#109]
The auth module is currently using two hard coded strings that should be set to be values from the config.

One is the JWT secret key, currently set to "dummy".

The other is the cookie parser secret, currently set to "prototype-secret".

This mondule needs a conf/config.schema.js file the same as the mongodb module in order to provide a place where these values can be defined.

**Comment by taylortom** [comment]
Closing, as no longer relevant

**Comment by taylortom** [comment]
Closing, as no longer relevant
