### ISSUE TITLE
Auth module feedback

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring#110]
Initial discussion of auth module, raising this here so that it doesn't get lost on gitter/can be discussed in next call.

Some suggestions for how we could restructure the code.

Oliver Foster
What's the rational for this:

    constructor(app, pkg) {
        this.routes = {};
        const routes = { secure: {}, unsecure: {} };
        Utils.defineGetter(this, 'routes', routes);
   }
Instead of this:

    constructor(app, pkg) {
        this._routes =  { secure: {}, unsecure: {} };
    },
    get routes() {
        return this._routes;
    }
In adapt_framework, one of our primary issues was trying to hide private variables and classes, we've spent some time undoing those. The general principle is to name stuff as private rather than to hide the reference, the trouble with a general practise of reference hiding is that people use it in different ways and often make bad choices which are hard to override if you need to hack them later.

at least with the second js code you know that the variable is private, you have an api to access it and the private stuff is available if you need it later. the former code is a bit harder and adds a custom helper. the former probably won't work as well with abstract syntax trees and intellisense.

Oliver Foster
function definitions nested in the constructor also have a similar problem in that they aren't defined for intellisense until the class is instantiated https://github.com/adapt-security/adapt-authoring-auth/blob/master/lib/utility.js#L37-L56
https://github.com/adapt-security/adapt-authoring-auth/blob/master/lib/utility.js#L89-L108 < these functions should probably live as statics on the class or in a separate file incase they need modification later
use lodash? https://github.com/adapt-security/adapt-authoring-core/blob/master/lib/utils.js#L92-L144

canstudios-nicolaw
All good points - thanks :)

This auth module was based off of a skeleton auth module and I haven't had time to clean up things from the skeleton. I've had the time I'm working on the rewrite cut short so was really trying to focus on getting the minimum working. I will try and look into these today - I'm just going to put them in an issue so they don't get lost on gitter in the meantime.

Tom Taylor
Don't really like the idea of false private (using a getter for a secret var)

Oliver Foster
i see the getter as the public api definition
without hindering any future overrides
at present even classes which extend don't have access to the secret var
it's the difference between a public, private and protected variable for me https://www.javacoffeebreak.com/faq/faq0002.html

Oliver Foster
obvs we don't have public, private and protected keywords in js
but the problem is still pretty much the same i guess

**Comment by taylortom** [comment]
Not relevant
