### ISSUE TITLE
adapt_framework schemas need converting to JSON Schema format

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#150]
- `$schema`: `http://json-schema.org/draft/2019-09/schema`
- `$id`: should be a unique identifier
- `additionalProperties`: `false`
- Custom keywords:
  * `isDate`: `true` converts to a Date
  * `isObjectId`: `true` converts to an ObjectId

**Comment by tomgreenfield** [comment]
🐙

**Comment by tomgreenfield** [comment]
Need to go through unrecognised fields and update Octopus accordingly.

**Comment by taylortom** [comment]
Done?
