### ISSUE TITLE
Look into server route errors on app start

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#164]
If framework is installed, the extra delay causes warnings with adding routes later on.

**Comment by tomgreenfield** [comment]
e.g.
```js
const exec = require('child_process').exec();
```

**Comment by taylortom** [comment]
Fixed, had to rejig the init order for `AbstractApiModule`s

**Comment by tomgreenfield** [comment]
Still happening for me bud.

**Comment by taylortom** [comment]
Fix attempt #2 🤞

**Comment by taylortom** [comment]
I can't replicate this one :worried: If you wouldn't mind, can you have a go at fixing?

**Comment by taylortom** [comment]
Is this still an issue?

**Comment by tomgreenfield** [comment]
Can no longer replicate; syntax errors are handled correctly.
