### ISSUE TITLE
ReferenceError on failing to load schema

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#171]
https://github.com/adapt-security/adapt-authoring-jsonschema/blob/8026754712eda2d317fdc2cd2e0338f640456f25/lib/jsonSchemaModule.js#L135
```console
(node:19020) UnhandledPromiseRejectionWarning: ReferenceError: file is not defined
    at JsonSchemaModule.registerSchema (D:\adapt-authoring\node_modules\adapt-authoring-jsonschema\lib\jsonSchemaModule.js:135:55)
```

**Comment by taylortom** [comment]
This will no longer be an issue as we don't load the schema when it's first registered, only when it's needed (i.e. validation).

Side-question: should we be validating a schema when it's registered?
