### ISSUE TITLE
Replace utils with lodash

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#173]
Do we have an abstraction here for the sake of abstraction?

- ~capitalise => _.capitalize~
- ~isArray => _.isArray~
- ~isBoolean => _.isBoolean~
- ~isFunction => _.isFunction~
- ~isNumber => _.isNumber~
- ~isObject => _.isObject~
- ~isString => _.isString~
- ~isPromise => ?~
- pluralise => ?
- trimUndefinedValues => ?

**Comment by tomgreenfield** [comment]
Agreed to remove functions with lodash equivalents.

**Comment by taylortom** [comment]
Done, leaving open for now to investigate other uses for lodash in existing code.
