### ISSUE TITLE
Look into separating json schema 'utilities' from json schema module 

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#177]
To remove the need to make module 'essential'

**Comment by taylortom** [comment]
See #51

**Comment by taylortom** [comment]
https://gist.github.com/taylortom/420764a635a69c7b217d86ce5b9db6ba

**Comment by tomgreenfield** [comment]
_Not convinced it's better than what we had, basically_

Tom Taylor

**Comment by taylortom** [comment]
wontfix
