### ISSUE TITLE
Expose framework info

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#181]
Might be useful for the framework module to expose information about the installed framework.

Could simply be the parsed package JSON – currently I do this manually:

```js
const frameworkData = await fs.readJson(`${this.frameworkPath}/package.json`);
```

**Comment by taylortom** [comment]
Added var `AdaptFrameworkModule#frameworkPkg` (AbstractModules already have a `pkg` var).
