### ISSUE TITLE
Investigate enforcing a load order

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#183]
`essentialApis` is already an array so could be utilised.

**Comment by taylortom** [comment]
I think we originally thought this might not be the best idea as it makes the app more fragile (i.e. if things break by not loading in the correct order)

**Comment by taylortom** [comment]
Can't remember if there was a specific use-case for this one, but anyway closing as that use-case hasn't presented itself again thus far...
