### ISSUE TITLE
Need to decide how user registration works

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#238]
Currently there's an unauthenticated `api/auth/local/register` route, but we'll likely need some kind of extra security around this + some way to customise how this works. Possible options:
1. Users are able to register themselves, and are given a default role. An existing user must then amend this as appropriate later. User is able to log into the system.
2. Users are able to register themselves, but are locked out of the system until approved + assigned a role by an admin.
3. Users are **not** able to register themselves, an existing user must do so.

Legacy uses approach 3.

**Comment by deltanetdan** [comment]
Most production environments would use option 3 and would not want to expose a register route. Perhaps having a configuration setting to enable options 1 or 2.

**Comment by canstudios-nicolaw** [comment]
I also vote for option 3 from the above. We personally wouldn't have any interest in options 1 or 2 even as a config setting.

**Comment by taylortom** [comment]
Have added `register:users` scope to the above route
