### ISSUE TITLE
Content item copy/paste

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#249]
Sort order

**Comment by tomgreenfield** [comment]
One thing to watch out for at the moment is [`ContentObject.updateSiblingSortOrder`](https://github.com/adaptlearning/adapt_authoring/blob/05733605ab8715008283bd32e095bd0c0d67c0d1/plugins/content/contentobject/index.js#L56-L87).

This operation shouldn't be performed if the create is part of a copy and paste where the sort orders of children need to be preserved.

**Comment by taylortom** [comment]
Done in https://github.com/adapt-security/adapt-authoring-content/commit/530ff32c54b9c0e842adf314eade2d28b141fe5e

**Comment by taylortom** [comment]
Sort order: https://github.com/adapt-security/adapt-authoring/issues/296
