### ISSUE TITLE
Formalise how roles should be defined

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#251]
This is currently done via the config file.

**Comment by taylortom** [comment]
We obviously need a way to provide some default roles, but not sure where this fits best. Don't mind how this is done, think at the very least we should have a separate config file for this (e.g. `/conf/roles.json`). Don't feel like it should go in with the roles module for some reason...

Legacy roles here: [adapt_authoring/lib/role](https://github.com/adaptlearning/adapt_authoring/tree/master/lib/role)

**Comment by canstudios-nicolaw** [comment]
Happy with a separate config file again. 

Currently the super admin role just has one line to say that it has all permissions, and the course creator has a long list of explicit permissions.

This makes it hard to tell the difference between the roles, if a super admin had a full list, then a diff of the super admin and course creator role files would show the difference which would come in handy.

**Comment by taylortom** [comment]
It was agreed to stick with the defining the roles in the config file for now (with defaults in the roles module)
