### ISSUE TITLE
 adapt-authoring-adaptFramework - export, publish and build output is missing content. Schema question.

### ISSUE THREAD

**Issue by deltanetdan** [adapt-security/adapt-authoring#267]
Export, publish and build contain empty arrays in the contentobject, article and block JSON files.

This is probably because _courseId is not defined in any schema for these collections and is therefore [added](https://github.com/adapt-security/adapt-authoring-adaptFramework/blob/master/lib/adaptFrameworkImport.js#L128) as a string rather than an objectId.

Adding a schema containing _courseId for these three collections could resolve the issue, if so where should this be added? In the framework schema (like config and components JSON) or in adapt-authoring-content selectively extending contentobjects, articles and blocks?

**Comment by taylortom** [comment]
Can I check you're pulling down my fork of the framework:
https://github.com/adapt-security/adapt-authoring-adaptFramework/blob/master/package.json#L17

...which has a 'content' schema that includes the _courseId
https://github.com/taylortom/adapt_framework/blob/master/src/core/schema/content.schema.json#L83-L90

**Comment by taylortom** [comment]
@deltanetdan can this one be closed now?

**Comment by deltanetdan** [comment]
Closing as fixed by using the framework fork mentioned above.
