### ISSUE TITLE
Framework update process

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#275]
We need some process to be able to do this painlessly

**Comment by taylortom** [comment]
- Framework now managed as an NPM dependency, so node_modules copy will be updated with an npm update
- If no framework found in temp, this is copied from node_modules
  - adapt install is also run at this point, with all plugins installed

**Comment by tomgreenfield** [comment]
* Clear the cached previews of courses? (if this still exists)

**Comment by taylortom** [comment]
Need to look into removing the installer as a local dependency and use npx

**Comment by taylortom** [comment]
Installer/updater has now been converted into an npx-runnable app.

**Comment by taylortom** [comment]
Closing this one for now, as will be resolved by https://github.com/adapt-security/adapt-authoring/issues/431
