### ISSUE TITLE
Need to decide on a consistent error handling approach

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#277]
i.e. the format we use to throw errors

***
Some strategy on how/when we handle errors (particularly how module authors should deal with errors in their modules)
***

A format I've used in a few places which works quite well (and isn't much work to set-up):
```js
class MyError extends Error {
  static MYCODE({ param }) {
    return new MyError(`Custom error message here ${param}`, 'MYCODE');
  }
  constructor(message, code) {
    super(message);
    this.code = code;
    this.statusCode = 400;
  }
}
// then created/thrown like so:
throw MyError.MYCODE(/* can pass data as required */);
```

Error then has a `statusCode`, which is used by the app's default Express error handler, and a string `code` which can be used as with other internal error types for more sophisticated checking (e.g. `if(e.code === 'MYCODE') {}`)

**Comment by oliverfoster** [comment]
The error is saying how it is to be handled by the rest of the app, it could be atomic enough that it just represents the error data only. Suggest removing the statusCode.

It's hard to see what problem the `MyError.MYCODE({ props, param: 'error message body' })`, `param` and `MYCODE` bits are intended to solve.

The main error message is hard coded in the `MYCODE` function but codes are used to identify specific errors.

Making a new error class to change the default error behaviour might be more complicated than necessary.

I've seen some brutally simple error systems floating around the interwebs:
```js
// Define your error codes as strings
const INVALID_AUTHENTICATION = 'INVALID_AUTHENTICATION';

// Expose them for use by other modules
module.exports = {
  INVALID_AUTHENTICATION
};

try {
  // Throw one, no need to invent the copy whilst coding
  throw new Error(INVALID_AUTHENTICATION);
} catch (error) {

  if (error.message === INVALID_AUTHENTICATION) {
    // You can compare errors this way, which is effectively coding the errors with the string constants
  }

  // Define your error copy externally
  const errors = {
    en: {
      [INVALID_AUTHENTICATION]: 'English invalid auth error'
    }
  };

  const lang = 'en';

  // Rethrow the error translated into the multi-lang copy
  const translated = errors[lang][error.message];
  // Could add a string replace here to resolve additional data on the error object into the text
  // Rework the error
  error.stack = error.stack.replace(error.message, translated);
  error.message = translated;

}


```

**Comment by taylortom** [comment]
So a more real-world example would be something like:
```js
throw AuthError.PERMS({ method, route })
```
Where method and route are used in the error message to give more contextual info. Something that's also useful is to be able to specify an HTTP status code along with an error.

Things I'd like to achieve:
- Be able to identify errors without using hard-coded strings (key-value idea works here)
- Be able to set specific HTTP codes along with an error type
- Be able to add extra data to the error for debugging

It makes sense to handle returning errors from one place (e.g. the default Express error handler), so we can do the translation stuff there. We could even have some kind of lookup at this point to match error codes to translated message + status codes, which would remove the need to store this on the error itself.

**Comment by taylortom** [comment]
Main npm module here: [adapt-authoring-errors](https://github.com/adapt-security/adapt-authoring-errors)

Latest attempt at a solution can be summarised as follows:
- Each Adapt module is able to define the errors it throws in [JSON format in a `/errors` folder](https://github.com/adapt-security/adapt-authoring-errors/blob/master/errors/adapt-errors.json). These are loaded in at system startup and stored as AdaptError instances.
- New [AdaptError](https://github.com/adapt-security/adapt-authoring-errors/blob/master/lib/AdaptError.js) class which extends Error, and stores the following (the below is defined by the errors JSON def mentioned above):
  - `code`: string, intended as a human-readable identifier (e.g. `NOT_FOUND`, `CONTENTPLUGIN_ALREADY_EXISTS`)
  - `statusCode`: HTTP status code used during request handling
  - `description`: a human-readable description of the error, which is only used for documentation purposes to allow for accurate translations of the error
  - `data`: _optional_ arbitrary supplemental data which provides extra context to an error (e.g. a URL for a specific API request failure, a file path for a file load error etc.). This data can then be used when translating errors for display via the UI.
- Central store of errors saved on main App instance. These are stored as getters on `this.app.errors`, to allow new error instances to be called each time the error is referenced, e.g. `throw this.app.errors.NOT_FOUND` will return a new instance each time it's referenced
- Errors are thrown as normal, by simply referencing the error on `this.app.errors`. Data can be added via the chainable setData function. Note that these errors are all still Error instances, so inherit that standard behaviour.
- Error messages are translated by the API server at the point they're returned to the client - using the error code, supplemental data and the existing lang/translation module.
