### ISSUE TITLE
Discuss ways to deal with bootstrapping processes in modules

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#278]
It's currently expected that devs should include their bootstrap process in the normal app boot process (i.e. before they set ready. In most cases this is fine, but there are occasions when the bootstrap process takes longer than the module load timeout (currently 10 secs) - load time is also dependent on the hardware running the app. 

It's currently possible for a module to specify a longer timeout, but any other modules which depend on it will also need to specify a longer timeout to avoid timing out themselves, so this isn't really an adequate solution.

One example of this is installing the framework bootstrap:
- Copy framework into place
- Install all plugins locally using the CLI  **<- this is the bottleneck**
- Add all plugins to DB
- Load all plugin schemas for use with AJV

In this specific case, the problem will be solved once the framework switches to using npm to manage deps, as these will all be resolved prior to starting the app.

The question is, do we need to build something into the app to solve these kinds of issues going forward (i.e. are we likely to have any other use cases like this.)

**Comment by oliverfoster** [comment]
What's the timeout for? Should it not just take as long as the hardware can process?

**Comment by taylortom** [comment]
The timeout's just really a usability thing to stop the app halting indefinitely during startup

**Comment by taylortom** [comment]
Also up until now, I hadn't even considered removing that timeout completely :joy:

**Comment by oliverfoster** [comment]
If it crashes at least you know something is broken.

**Comment by taylortom** [comment]
wontfix, have refactored load process to remove timeout
