### ISSUE TITLE
Need to fix builds for spoor tracking

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#292]
No tracking IDs

**Comment by taylortom** [comment]
Should this be stored in the DB, or reset every build?

**Comment by canstudios-nicolaw** [comment]
I think these should be fixed in the database. If I have an adapt course in an LMS and I update the adapt course and re-upload I would expect all the tracking ids to stay the same.

**Comment by taylortom** [comment]
Done in https://github.com/adapt-security/adapt-authoring-spoortracking
