### ISSUE TITLE
Schemas need updating to draft 2019-09

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#312]
Very minor changes, the most likely to affect us:

- New `$anchor` keyword replaces the #plain-name form of `$id`, with a different syntax and approach
- `definitions` is now `$defs` (don't think we've used this yet)

See: https://json-schema.org/draft/2019-09/release-notes.html

**Comment by tomgreenfield** [comment]
Please confirm Ajv plays well with `$anchor`.

**Comment by taylortom** [comment]
Fixed
