### ISSUE TITLE
Trailing comma in spoor config.schema.json

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#345]
Adding here, so as not to confuse any framework people
https://github.com/adaptlearning/adapt-contrib-spoor/blob/v3.6.0-alpha.1/schema/config.schema.json#L133

**Comment by tomgreenfield** [comment]
Fixed; [this dependency](https://github.com/taylortom/adapt_framework/blob/913e29c4d085917a34aa69ffc12e1db872baf283/adapt.json#L23) needs bumping to `3.8.0-alpha.1`.
