### ISSUE TITLE
Queries using advanced MongoDB formats and ObjectIds return incorrect results

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#348]
The MongoDB JS driver isn't able to interpret which values should be ObjectIds (all strings which are ObjectIds must be converted to an `ObjectId()` for any queries to work). We get around this for most queries by running the query data through the validator, which runs a few helpers to make sure incoming types are converted. However, this won't work for edge-cases where the incoming data uses mongo's more advanced querying, e.g. 
```
{ createdBy: { $ne: "xxxxxxxxxx" } }
```
As the above format doesn't fit the value expected by the schema (i.e. string).

**Comment by oliverfoster** [comment]
Does the query to be executed come from an external source?
Can you describe the use-case in a bit more detail?
Which query API? Aggregate pipeline? Or just standard query.

**Comment by taylortom** [comment]
Just come across this one again. As a partial fix, I do a quick validation to incoming queries which automatically converts any strings to ObjectIds for standard queries (where the query itself is just an object of values, e,g, `{ _id: 'XXX', createdBy: 'XXX', size: 10 }`). 

Where this falls over is when using some of the more advanced mongo query props like `$in` for arrays of ObjectIds, as this passes through the validator as an unknown property. The query then obvs fails to match anything because it's looking for ObjectIds but only has strings.

An example query for a course with a specific tag (needs to support multiple tags in the query):
```
course {
  createdBy: 60ffe6cd436f6961cf311292,
  title: { '$regex': '.*.*', '$options': 'i' },
  tags: { '$in': [ '610185a85727cd8c4d3dabcd' ] },
  _type: 'course'
}

```
The createdBy value gets  converted to an ObjectId as expected, but the title & tags fields fail the validator check for obvious reasons.

**Comment by taylortom** [comment]
Hold on, apparently you can use the format `{ $oid: 'XXX' }` for ObjectIds as a hex string

**Comment by taylortom** [comment]
Fixed
