### ISSUE TITLE
Look into adding default values for config paths

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#354]
Currently, users are required to set each directory attribute manually in the config file. It would be nice to be able to set a default value in the schema for these directory attributes. 

For all but the most advanced of users defaults will be fine and preferable (e.g. root dir is `process.cwd()`, temp is `/temp` from the root etc,), 

Need to check whether relative paths work.

**Comment by taylortom** [comment]
Most paths rely on the rootDir attribute, which must be absolute. Other than that, I've found no other issues yet.

**Comment by tomgreenfield** [comment]
`uploadTempDir` now exists in core.

```js
"adapt-authoring-core": {
  "rootDir": process.cwd(),
  "uploadTempDir": os.tmpdir()
}
```
We have discussed:
* Making `rootDir` not a required attribute
* Dropping the default for `uploadTempDir` (currently `"temp/formidable"`)
* Most users would use process/OS defaults. Formidable currently defaults to the OS's temp directory anyway but may possibly want to explicitly set it in case  `uploadTempDir` is ever used by something else without the fallback
* Need to check that any current cleanup code doesn't wipe the entire OS temp directory
* Other modules (assets/contentplugin) still need rationalising to use the `fileUploadParser` middleware

**Comment by taylortom** [comment]
Done
