### ISSUE TITLE
Need a schema for the vanilla variables

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#361]
As requested, the code looks for a schema registered with the $anchor with the theme's `theme` attribute followed by `-theme`, so `vanilla-theme` in this case.

**Comment by tomgreenfield** [comment]
I've added this to Vanilla 5.4.0-alpha.3. Need to get this onto the testing instance somehow.

Variables currently sit in the root properties object and are still grouped by fieldsets.
