### ISSUE TITLE
Mailer init needs to be more user-friendly

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#367]
Specifically checking config settings on start-up. Currently if the config is invalid, the module doesn't init fully, which results in errors later on if attempting to send a mail.

Could do with discussing how we want to approach this.

**Comment by iklemm** [comment]
I will have a look.

**Comment by fkcailiniyazi** [comment]
Is this issue still open?

**Comment by taylortom** [comment]
Fixed
