### ISSUE TITLE
Mailer connection URL validation too strict

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#368]
It currently fails for local mail servers using `smtp://localhost`

**Comment by fkcailiniyazi** [comment]
I've just found out that Ingo has already fixed the problem and sent a pull request.
https://github.com/adapt-security/adapt-authoring-mailer/pull/9

**Comment by taylortom** [comment]
Ah I'd missed that, looks good :) 
Have merged, as we've not been going through any review process yet.
