### ISSUE TITLE
Supported asset mime types should be set in config

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#374]
See assetUtils.js `_supportedMimetypes`.

_taken from TODO comment_

**Comment by iklemm** [comment]
I wonder if we might better remove this mimetype-data from config. 

Reason: A user can't really configure here anything. He can't just add a mimetype without prior extending the module to make it handle a new type. Only thing he could do is to reduce the supported mimetypes, but is there a use case for this? To me it seems  just redundant to have the supported mimetype in config.  What do you think about it?

**Comment by taylortom** [comment]
:+1: let's close this one
