### ISSUE TITLE
Assets utils test needed for getMaxThumbSize

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#376]
Write test to getMaxThumbSize 

_taken from TODO comment_

**Comment by fkcailiniyazi** [comment]
Fixed with commit [2d2711f788bca0f93a45dbadc21ed81b1c3f37b7](https://github.com/adapt-security/adapt-authoring-assets/commit/2d2711f788bca0f93a45dbadc21ed81b1c3f37b7)
