### ISSUE TITLE
AssetsRepository: throw error if repositoryPath is not accessible

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#378]
See `AssetsRepository#init`

_taken from TODO comment_

**Comment by fkcailiniyazi** [comment]
Fixed with commit [2d2711f788bca0f93a45dbadc21ed81b1c3f37b7](https://github.com/adapt-security/adapt-authoring-assets/commit/2d2711f788bca0f93a45dbadc21ed81b1c3f37b7)
