### ISSUE TITLE
Box menu _backgroundStyles throwing error on save

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#381]
The UI passes `null` values currently. Fields either need to be set as required, or have a default value, not sure which is more appropriate.

**Comment by tomgreenfield** [comment]
It's an error in the previous schema that's been brought across – `""` needs to be added to enums.

**Comment by taylortom** [comment]
Duplicate of https://github.com/adapt-security/adapt-authoring/issues/360#issuecomment-769116628

**Comment by tomgreenfield** [comment]
Now fixed in Box Menu 5.2.0-alpha.3.
