### ISSUE TITLE
Content plugins need schema name specifying

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#383]
AJV now strips off any attributes which aren't specified in the schema.

We currently use the component/extension/menu/theme attributes when inferring the schema to use for validation (e.g. `vanilla-theme`). This is no longer stored in the DB (and can't be going forward unless we introduce different schemas for each type).

I propose we add a schemaName attribute or similar to the bower.json to get around this.

**Comment by taylortom** [comment]
think it seems sensible to switch to using the `targetAttribute` in place of the remove values, and introduce these for all plugin types.

For now, I've added a dirty hack to `editorThemingView` to strip the `_` from the target attribute (which will work for now until all schemas are renamed).

**Comment by taylortom** [comment]
For now, we're using `targetAttribute` with the leading underscore dropped (just a `"".slice(1)` in the code), but we need a more permanent solution.

Note: we need targetAttributes adding to all plugins which don't currently have one (@tomgreenfield)

**Comment by tomgreenfield** [comment]
The only ones that don't yet are Blank and Tutor...but they also don't need a schema.

**Comment by tomgreenfield** [comment]
> Note: we're only doing a `"".slice(1)`

Worth improving the hack with a `if (targetAttribute.startsWith('_'))`?

**Comment by taylortom** [comment]
Fixed
