### ISSUE TITLE
Should frontend build automatically

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#387]
When the app is started after an `npm update` there is a broken build.

**Comment by taylortom** [comment]
Done. 

UI will now rebuild if the build dir doesn't exist (`/node_modules/adapt-authoring-ui/build` by default - also see https://github.com/adapt-security/adapt-authoring-ui/issues/67). A rebuild can be forced with the flag --rebuild-ui (`npm start -- --rebuild-ui`)
