### ISSUE TITLE
Build dir should be configurable

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#390]
Atm this is created in the `adapt-authoring-ui` module root, but would ideally be somewhere more obvious (probably the temp folder).

**Comment by tomgreenfield** [comment]
Let's be careful we don't lose the static source for development purposes – find that very useful!

**Comment by taylortom** [comment]
Had a quick look at this, but it's not a clean easy fix due to the hard-coded nature of the paths. Would need to either switch the Gruntfile to use vars, or move the build files post-build. As this is only a nice-to-have, it's probably not worth it atm.

**Comment by taylortom** [comment]
Won't fix
