### ISSUE TITLE
Got error during unzip a .zip file

### ISSUE THREAD

**Issue by memeteli** [adapt-security/adapt-authoring#395]
The unzipping function worked before, but now as I've tested it, it gives the following error back:
`
{
    "_messagePrefix": "Data validation failed",
    "name": "DataValidationError",
    "errors": [
        "/createdBy should be string"
    ]
}
`

Note: uploading a zip file as a single asset is working.

**Comment by taylortom** [comment]
I'm not aware of an unzipping function, is there a way to do this via the UI or is it an API feature

**Comment by taylortom** [comment]
Closing as not supported currently.
