### ISSUE TITLE
Error prevents install completion

### ISSUE THREAD

**Issue by deltanetdan** [adapt-security/adapt-authoring#406]
After cloning the adapt-authoring repo and running:
npm install
node bin/cli install

The browser based install fails on submitting 'Create user' form with the following error/s:

POST http://localhost:8080/registeruser [HTTP/1.1 500 Internal Server Error 7ms] 
response error: Error, TypeError: Cannot read property '_id' of undefined

Uncaught (in promise) Error: Error, TypeError: Cannot read property '_id' of undefined line 13 > injectedScript:218:23

## Versions
  - Node.js Version: v14.17.0
  - MongoDB Version: v4.0.20
  - Operating System: OSX 10.14.6
  - Browser: Firefox 89.0.2

**Comment by taylortom** [comment]
Should be fixed

**Comment by deltanetdan** [comment]
This is now fixed.
