### ISSUE TITLE
Need to be able to delete assets via the code API

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#415]
Currently I think this is only possible using the REST API.

**Comment by taylortom** [comment]
I would possibly look at renaming the existing `deleteAsset` function to `deleteAssetHandler` (as it's an express handler function), and call the new `deleteAssetLocal` `deleteAsset` instead.

**Comment by fkcailiniyazi** [comment]
I've updated the names, as you said.
