### ISSUE TITLE
Asset records should only point to a single asset file

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#416]
I've seen references in the code that point to the possibility that this can occur. This isn't necessary in the refactor (not sure why it was built that way in legacy, it doesn't make sense to me...)

**Comment by fkcailiniyazi** [comment]
I remember that we had a discussion about them, but we didn't have a solution about it, or should we create duplicated files on repository so that each asset records will only point to a single asset file?

**Comment by taylortom** [comment]
Yep we didn't really come to a conclusion with this. Let's defer until after beta,

**Comment by fkcailiniyazi** [comment]
I think we could try to use UUID package to generate a unique ID for each asset file instead of hashing it. 
[uuid](https://www.npmjs.com/package/uuid)

**Comment by taylortom** [comment]
Fixed
