### ISSUE TITLE
Installer doesn't show advanced settings

### ISSUE THREAD

**Issue by fkcailiniyazi** [adapt-security/adapt-authoring#420]
It should show advanced settings form after selecting the checkbox, but it doesn't show the form and logs an error on console after clicking submit button:

![image](https://user-images.githubusercontent.com/54360982/127166661-bc214cca-d9d5-4908-a27e-190f9d01eb4c.png)

**Comment by fkcailiniyazi** [comment]
It seems that the version of npm caused this problem. I downgraded the version to 6.14.13 and the problem disappeared.

**Comment by taylortom** [comment]
I think we can ignore this for now, and readdress when we come to integration with node 16/npm 7
