### ISSUE TITLE
Installer hangs on npm install

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#435]
Need to look into the child process

**Comment by oliverfoster** [comment]
This may be associated with this framework pr https://github.com/adaptlearning/adapt_framework/pull/3183 and this dependency https://github.com/adapt-security/adapt-authoring-adaptFramework/blob/master/package.json#L19

Although it only came into effect in v5.17, if you npm is cloning the repo before switching versions it could be an issue as master branch is v5.17+

**Comment by taylortom** [comment]
Closing as no longer applicable now the framework's been removed as an npm dep
