### ISSUE TITLE
Can not select a plugin to be added to new course by default

### ISSUE THREAD

**Issue by fkcailiniyazi** [adapt-security/adapt-authoring#511]
we got the following error:
![image](https://user-images.githubusercontent.com/54360982/162712584-0edb19ff-9bf2-4684-9828-f674ee3231bf.png)

 and by refresh the page the selected plugin will be unselected again.

**Comment by taylortom** [comment]
Response JSON as follows:
```json
{
  "code":"MONGO_ERROR",
  "message":"A MongoDB error occurred while attempting to update contentplugins"
}
```

**Comment by taylortom** [comment]
Apologies, the npm module which takes care of this wasn't installed 😅 
Should be working now

**Comment by fkcailiniyazi** [comment]
👍
