### ISSUE TITLE
Unable to import source

### ISSUE THREAD

**Issue by fkcailiniyazi** [adapt-security/adapt-authoring#516]
By importing source, we get:

![image](https://user-images.githubusercontent.com/54360982/162744447-45fe4081-8179-43cc-b1a8-bf722e807ae7.png)

**Comment by taylortom** [comment]
```
2022-04-12T12:40:42.667Z error server {}
2022-04-12T12:40:42.660Z error adaptframework failed to import course, TypeError: Cannot read properties of undefined (reading '_type')
2022-04-12T12:40:42.509Z error adaptframework {"code":"MISSING_SCHEMA_NAME","statusCode":400,"meta":{"description":"Schema name is not defined"}}
```

**Comment by taylortom** [comment]
Was this an export from the authoring tool itself, or a framework course?

**Comment by taylortom** [comment]
This should now be fixed!

**Comment by fkcailiniyazi** [comment]
It works, but I got ``2022-04-19T13:14:52.612Z error courseassets Failed to insert courseasset document, TypeError: Cannot read properties of undefined (reading 'toString')`` this on console.

**Comment by taylortom** [comment]
I'm not able to replicate this one now, I think it may have been fixed in the framework module. Can you try:
- Pull the latest code from master
- Install the latest npm deps
- Create a new course & export
- Import the new course

**Comment by fkcailiniyazi** [comment]
I think it is fixed now 👍
