### ISSUE TITLE
Course preview type error

### ISSUE THREAD

**Issue by KristofferBroberg** [adapt-security/adapt-authoring#517]
1. Create course
2. Add some content
3. Run preview

Terminal:

```
info adaptframework running preview for course '6257ee4841f73a4d6400eadb'
file:///Users/u0065422/adapt/node_modules/adapt-cli/lib/integration/AdaptFramework/build.js:33
        e.raw = stdout.match(/>> Error:\s(.+)\s/)[1]
                                                 ^

TypeError: Cannot read properties of null (reading '1')
    at file:///Users/u0065422/adapt/node_modules/adapt-cli/lib/integration/AdaptFramework/build.js:33:50
    at ChildProcess.exithandler (node:child_process:390:7)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

MongoDB 5.0.6
Node 16.14.0
Chrome latest
OS X 10.15.7

**Comment by deltanetdan** [comment]
👍 also getting this error. Partial fix by @taylortom [here](https://github.com/adaptlearning/adapt-cli/pull/164). However previewing with this fix still returns an error due to [stderr](https://github.com/adaptlearning/adapt-cli/blob/master/lib/integration/AdaptFramework/build.js#L30) returning the following:

`Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}`

**Comment by taylortom** [comment]
Are you guys getting this from any specific course config? I'm not able to replicate with a fresh course (similar issue here: https://github.com/adapt-security/adapt-authoring-ui/issues/177)

**Comment by KristofferBroberg** [comment]
Here´s my build/course/config.json

```
{
  "_id": "6257ee4841f73a4d6400eadc",
  "_courseId": "6257ee4841f73a4d6400eadb",
  "_type": "config",
  "createdBy": "6257ed4ceb1359603a2bd1ed",
  "updatedAt": "2022-04-14T09:50:00.683Z",
  "createdAt": "2022-04-14T09:50:00.194Z",
  "_extensions": {},
  "_enabledPlugins": [
    "adapt-contrib-boxMenu",
    "adapt-contrib-vanilla",
    "adapt-contrib-text"
  ],
  "_theme": "adapt-contrib-vanilla",
  "_menu": "adapt-contrib-boxMenu",
  "_completionCriteria": {
    "_requireContentCompleted": true,
    "_requireAssessmentCompleted": false,
    "_shouldSubmitScore": false
  },
  "_defaultLanguage": "en",
  "_defaultDirection": "ltr",
  "_accessibility": {
    "_isEnabled": true,
    "_isSkipNavigationEnabled": true,
    "_ariaLevels": {
      "_menu": 1,
      "_menuGroup": 2,
      "_menuItem": 2,
      "_page": 1,
      "_article": 2,
      "_block": 3,
      "_component": 4,
      "_componentItem": 5,
      "_notify": 1
    },
    "_options": {}
  },
  "_fixes": {
    "_imgLazyLoad": true
  },
  "screenSize": {
    "small": 520,
    "medium": 760,
    "large": 900
  },
  "_questionWeight": 1,
  "_drawer": {
    "_showEasing": "easeOutQuart",
    "_hideEasing": "easeInQuart",
    "_duration": 400
  },
  "_generateSourcemap": false,
  "_forceRouteLocking": true,
  "_disableAnimationFor": [],
  "_logging": {
    "_isEnabled": true,
    "_level": "info",
    "_console": true,
    "_warnFirstOnly": true
  },
  "_scrollingContainer": {
    "_isEnabled": true,
    "_limitToSelector": ""
  },
  "themeSettings": {},
  "_languagePicker": {
    "_isEnabled": false,
    "title": "",
    "displayTitle": "",
    "body": "",
    "_showOnCourseLoad": true,
    "_languagePickerIconClass": "icon-language-2",
    "_restoreStateOnLanguageChange": false,
    "_classes": ""
  },
  "_trickle": {
    "_completionAttribute": "_isComplete"
  },
  "tags": []
}

```

**Comment by deltanetdan** [comment]
Config is attached. Course created using "Add new course" in AT. AT is local install. The grunt command works OK with no errors in the stdout.

Node: v16.14.2
NPM: 8.5.0
MongoDB: 4.4.10
MacOS 11.6.5
[config.json.zip](https://github.com/adapt-security/adapt-authoring/files/8512469/config.json.zip)

**Comment by KristofferBroberg** [comment]
Don't know if this has anything to do with it..

I installed grunt and ran Grunt check-json. Got `Error: Unable to read "../adapt/temp/builds/1649929868144/src/course/config.json" file (Error code: ENOENT).`

There´s no course folder in src. My config.json is in ../adapt/temp/builds/1649929868144/**build**/course/config.json"

**Comment by taylortom** [comment]
The adapt-cli API expects the course folder to be in build, so shouldn't be a problem

**Comment by KristofferBroberg** [comment]
OK. FYI. Did a fresh install. Completely removed MongoDB 5.x and installed 4.4. Created course. Still got this error.
