### ISSUE TITLE
Missing API endpoint when requesting Password reset email

### ISSUE THREAD

**Issue by canstudios-kent** [adapt-security/adapt-authoring#520]
Requesting password reset email creates an API error log. 
error server {"code":"ENDPOINT_NOT_FOUND","statusCode":404,"meta":{"description":"API endpoint does not exist","data":{"endpoint":"The missing endpoint"}},"data":{"endpoint":"/api/createtoken"}}

The error is not indicated to the user on the password reset form UI. From the user's perspective, the email is never sent to them.

Steps to reproduce:
1. From the login screen, click "Forgot your password?".
2. Enter a valid user's email address. Click Continue.
3. If API logs are accessible, notice the error that appears.

**Comment by taylortom** [comment]
Fixed.

### Note: SMTP not enabled on the testing server, so no actual email will be received

**Comment by canstudios-kent** [comment]
Reset password emails are now being sent.
