### ISSUE TITLE
Sending password reset mail to other users does not occur

### ISSUE THREAD

**Issue by canstudios-kent** [adapt-security/adapt-authoring#521]
Super users can request a password reset email for other users.
However, the logs show a warning when attempting to do so:

`2022-04-21T11:03:07.620Z warn mailer could not send email, SMTP is not enabled`

From the user's perspective, the act of sending the password reset email is "completed" - no error messages appear to them.

Steps to reproduce:
1. As a Super user, navigate to "User management". 
2. Select a user. Click "Reset password".
3. Select "Yes I'm sure".
4. If logs are accessible, notice that a warning appears. The password reset email is not sent.

**Comment by taylortom** [comment]
SMTP isn't currently enabled on the testing server, so there shouldn't be anything to do here

**Comment by canstudios-kent** [comment]
Reset password emails are now being sent.
