### ISSUE TITLE
Missing API endpoint for uploading asset

### ISSUE THREAD

**Issue by canstudios-kent** [adapt-security/adapt-authoring#522]
The user can go through the process of selecting and confirming a file to upload into Asset management. However, the asset will not be available in the Asset management area.

If the server logs are available, you can see an error:
`2022-04-21T12:03:56.976Z error server {"code":"ENDPOINT_NOT_FOUND","statusCode":404,"meta":{"description":"API endpoint does not exist","data":{"endpoint":"The missing endpoint"}},"data":{"endpoint":"/api/assets"}}`

From the user's perspective, no error message is given.

Steps to reproduce:

1. In Asset Management, click "Upload new asset".
2. Select a file to upload. Fill in all mandatory fields.
3. Click "Save". If API logs are accessible, notice the error that appears.

**Comment by taylortom** [comment]
Fixed

**Comment by canstudios-scottd** [comment]
Verified on testing
