### ISSUE TITLE
503 error occurs when using Filter by Name search field in Asset Management

### ISSUE THREAD

**Issue by canstudios-kent** [adapt-security/adapt-authoring#523]
The server instance becomes unavailable when attempting to use the "Filter by Name" field in the Asset management area. This occurs for a few minutes, and then the instance becomes available again. Unfortunately, the logs reset when this occurs.

Steps to reproduce:
1. In Asset Management, enter a term in the "Search by name" field.
2. Refresh the page. Notice the 503 error.

**Comment by taylortom** [comment]
This immediately crashes the server, oops 😂

**Comment by taylortom** [comment]
Fixed

**Comment by canstudios-scottd** [comment]
verified on testing
