### ISSUE TITLE
Cannot scroll down Asset selection modal

### ISSUE THREAD

**Issue by canstudios-kent** [adapt-security/adapt-authoring#525]
When the user clicks "Select an Asset", a modal listing available relevant assets is shown. However, the user cannot scroll down the modal should the asset list go offscreen.

Steps to reproduce:
1. Ensure that there is at least 20 images available in the the Asset management area.
2. In a course, add a Graphic component.
3. In the Graphic component's settings, click "Select an Asset". 
4. Depending on your browser window width, there should be additional rows of assets that are off modal. Attempt to scroll down the modal. Notice that you cannot scroll further down the asset selection modal.

**Comment by taylortom** [comment]
Fixed

**Comment by canstudios-scottd** [comment]
Verified on testing
