### ISSUE TITLE
Npx update - empty screen

### ISSUE THREAD

**Issue by KristofferBroberg** [adapt-security/adapt-authoring#557]
AA rc1
Win 10

Running npx adapt-security/at-utils update --prerelease DIR shows green empty screen with attached console.

[localhost-1666770577823.log](https://github.com/adapt-security/adapt-authoring/files/9867316/localhost-1666770577823.log)

**Comment by taylortom** [comment]
I've just pushed out a load of changes to the installer which should hopefully fix this 😊

**Comment by taylortom** [comment]
I've just pushed out a load of changes to at-utils which should hopefully fix this 😊
