### ISSUE TITLE
Assessment ID and enable setting not saving

### ISSUE THREAD

**Issue by joe-allen-89** [adapt-security/adapt-authoring#606]
### What happened?

When creating an assessment the ID and enable settings do not save correctly. 

### Steps to reproduce

- Add an assessment to an article
- Select 'make this article an assessment' and add an assessment ID
- Click save
- Edit the article and check the assessment ID and checkbox...

### Authoring tool version

Latest

### Framework version

Latest

**Comment by taylortom** [comment]
Can't replicate this one on the latest code

**Comment by kineopete** [comment]
Confirm can't replicate in the latest 1.0.0-rc.2
