### ISSUE TITLE
Authentication: Initial setup

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring#61]
The aim of this task is to lay the foundations for future authentication work.

- Create users collection, this should have the following fields at this stage:  "_id", "auth", "email", "password"
- Setup local passport authentication. This should be an independent auth module which will be started on server boot.
- Create a user record which can be manually pasted into the collection as a start point

At the end of this body of work, it should be possible to use something like Postman to send the API login requests with an email/password and receive a success or fail depending on whether the password is correct.

**Comment by taylortom** [comment]
Done https://github.com/adapt-security/adapt-authoring-auth
