### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring#62]
The purpose of this issue is to set up basic user management. No roles/groups will be present at this stage.

- API routes should be implemented for user CRUD tasks. 
- A user should supply a password on creation and this should be encrypted with bcrypt
- It should be possible to disable a user account

At the end of this task, it should be possible to use something like Postman to send API requests to CRUD and disable users. Created users should have encrypted passwords and be able to use the login API to authenticate.

**Comment by taylortom** [comment]
Done https://github.com/adapt-security/adapt-authoring-users
