### ISSUE TITLE
Set password page error message unclear

### ISSUE THREAD

**Issue by guywillis** [adapt-security/adapt-authoring#624]
### What happened?

When I was unable to set my password I received an error message that wasn't particularly helpful. It returned an undefined error message. 

### Steps to reproduce

* I was set up a new account on a v1.0.0-rc.4 instance of the Authoring Tool. 
* I proceeded to follow the 'Set your Adapt password' link from the received email. 
* I was unable to set my password as I was falling foul of the password requirements. 
* The error message pop up that appeared after trying to input a password shorter than 12 characters returned an 'undefined' error message 

### Authoring tool version

1.0.0-rc.4

**Comment by taylortom** [comment]
Closing as duplicate of https://github.com/adapt-security/adapt-authoring/issues/623
