### ISSUE TITLE
CKeditor licensing?

### ISSUE THREAD

**Issue by tomgross** [adapt-security/adapt-authoring#627]
### What happened?

CKeditor 4 has reached EOL in June 2023. (See https://ckeditor.com/ckeditor-4/)

Adapt is using 4.5.7. Latest of 4 series is [4.23.0-lts](https://github.com/ckeditor/ckeditor4/releases/tag/4.23.0-lts)

### Expected behaviour

Use a supported version of a WYSIWYG-editor.

### Steps to reproduce

Check ckeditor version

### Authoring tool version

master / 1.0.0rc4

**Comment by taylortom** [comment]
Many thanks for logging. This was actually a known 'issue' (although it doesn't seem to have an associated ticket). 

I've created one for the work here: https://github.com/adapt-security/adapt-authoring-ui/issues/273
