### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring#63]
The purpose of this issue is to put basic role functionality in place.

- Create role collection
- Users should get assigned a role on creation
- Propose how role permissions will be defined (currently each role contains a series of statements) and agree on this. Define role permissions in collection. 
- Roles collection should be initialised on app startup

- _Possibly_ start to implement role permissions at this stage (this might get split into it's own issue to be worked on at a later date)

At the end of this body of work, it should be mandatory for new users to have a role. The role will be sent in the API request and rejected if it does not exist. 

A users role might not have much effect at the end of this issue.

**Comment by taylortom** [comment]
Done, https://github.com/adapt-security/adapt-authoring-roles
