### ISSUE TITLE
Authentication: Longer term

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adapt-security/adapt-authoring#65]
The things in this issue need to be addressed although I'm not sure it is putting more detail in them until the project is a little further along as they are subject to change.

- Ability to decide what happens to a users courses when the user is deleted
- Create initial user on app install - specify email + password
- Dashboard filtering by group
- Lock down routes so that they can only be accessed by authenticated users
- Add role/group permission behaviour

**Comment by taylortom** [comment]
Have moved these to separate issues where appropriate
