### ISSUE TITLE
Asset management additional CRUD API routes

### ISSUE THREAD

**Issue by dancgray** [adapt-security/adapt-authoring#68]
This issue if for tasks in addition to the basic asset upload/download.
- [ ] Able to permanently delete an asset (must)
- [ ] Able to replace an asset file (should)
- [ ] Able to update the title, description and tags for an asset (must)
- [ ] Able to upload a zip file containing multiple assets (should)
- [ ] Able to tag all assets and add a title and description when uploading and asset file or multiple files in a zip (should)

**Comment by taylortom** [comment]
Moved to assets module
