### ISSUE TITLE
Assets - additional query requirements

### ISSUE THREAD

**Issue by dancgray** [adapt-security/adapt-authoring#69]
In addition to basic querying of assets, the module should be able to do the following:

- [ ] Able to query which courses an asset is used in (should)
- [ ] Able to sort queried assets by size (should)
- [ ] Super admin able to query and view all assets that are not used by any content (should)

This task should be completed after all of the must have features are complete. Please add any other should have asset querying requirements to this ticket.

**Comment by taylortom** [comment]
Moved to assets module
