### ISSUE TITLE
Need a way to compose logging + translation

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#74]
i.e. add `this.log` + `this.t` functions to any class.

Currently too much duplication because of this:
- TODO

**Comment by tomgreenfield** [comment]
Agreed that these are useful shortcuts and a way to enfore module name in the logs, for example.

**Comment by taylortom** [comment]
Not sure this is a specific problem any more; should be dealt with on a case-by-case basis.
